ALTER TABLE `advertiser_macros` ADD `macro` VARCHAR( 90 ) NOT NULL AFTER `name`;

INSERT INTO `advertiser_macros` (`id`, `advertiser_id`, `name`, `macro`, `event`, `build`, `description`, `status_id`) VALUES
(1, 1, 'pub_id', '{PUB_ID}', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(2, 1, 'idfa', '{IDFA}', NULL, NULL, 'Google Advertising ID / iOS IDFA/ Android ID (only for Amazon, and it is lowercased, then sha1 hashed)', 1),
(3, 1, 'did', '{DID}', NULL, NULL, 'Click ID', 1),
(4, 1, 'campaign_name', '{CAMPAIGN_NAME}', NULL, NULL, 'Campaign Name', 1),
(5, 1, 'ip', '{IP}', NULL, NULL, 'IP Address', 1),
(6, 1, 'cc', '{CC}', NULL, NULL, 'Country Code', 1),
(7, 103, 'idfa', '%{idfa}', NULL, NULL, 'iOS IDFA', 1),
(8, 103, 'identifier_for_advertising', '%{identifier_for_advertising}', NULL, NULL, 'Google Advertising ID', 1),
(9, 103, 'app_id', '%{app_id}', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(10, 103, 'impression_id', '%{impression_id}', NULL, NULL, 'Impression ID', 1),
(11, 103, 'campaign_id', '%{campaign_id}', NULL, NULL, 'Campaign ID', 1),
(12, 105, 'idfa', '{IDFA}', NULL, NULL, 'iOS Advertiser ID', 1),
(13, 105, 'ip', '{IP}', NULL, NULL, 'IP address', 1),
(14, 105, 'sub_publisher', '{sub_publisher}', NULL, NULL, 'Publisher ID', 1),
(15, 105, 'country_code', '{country_code}', NULL, NULL, 'Non-standard country ISO code; hardcoded in the tracking URL as 0086', 1),
(16, 105, 'callback_param', '{callback_param}', NULL, NULL, 'Click (to pass @ post back)', 1),
(17, 107, 'token', '{token}', NULL, NULL, 'GMO internal click ID; to be passed at post back', 1),
(18, 109, 'iquclickidhere', '{iQUclickidhere}', NULL, NULL, 'Iqu internal click ID; to be passed at post back', 1),
(19, 109, 'iquofferidhere', '{iQUofferidhere}', NULL, NULL, 'Iqu internal offer ID; to be passed at post back', 1),
(20, 109, 'subid', '{subID}', NULL, NULL, 'Sub publisher', 1),
(21, 109, 'ip', '{ip}', NULL, NULL, 'IP Address', 1),
(22, 11, 'transaction_id', '{transaction_id}', NULL, NULL, 'Unique click ID from Unilead (previously this macro was {click_id})', 1),
(23, 11, 'offer_id', '{offer_id}', NULL, NULL, 'Unique ID for each campaign', 1),
(24, 11, 'affiliate_id', '{affiliate_id}', NULL, NULL, 'Sub publisher', 1),
(25, 11, 'ios_ifa', '{ios_ifa}', NULL, NULL, 'iOS IDFA', 1),
(26, 11, 'google_aid', '{google_aid}', NULL, NULL, 'Google advertiser ID', 1),
(27, 111, 'subid', '${SUBID}', NULL, NULL, 'internal click ID that we will pass at post back', 1),
(28, 111, 'zoneid', '{zoneid}', NULL, NULL, 'Sub Publisher; ID of the site where the add was clicked', 1),
(29, 113, 'device_ad_id', '[DEVICE_AD_ID]', NULL, NULL, 'Google Advertising ID / iOS IDFA', 1),
(30, 113, 'site_id', '[SITE_ID]', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(31, 113, 'clk_id', '[CLK_ID]', NULL, NULL, 'Click ID', 1),
(32, 113, 'track_id', '[TRACK_ID]', NULL, NULL, 'Track ID', 1),
(33, 113, 'ip', '[IP]', NULL, NULL, 'IP Address', 1),
(34, 115, 'idfa', '[=IDFA=]', NULL, NULL, 'iOS IDFA', 1),
(35, 115, 'gaid', '[=GAID=]', NULL, NULL, 'Google Advertising ID', 1),
(36, 115, 'subid', '[=SUBID=]', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(37, 115, 'publisherid', '[=PUBLISHERID=]', NULL, NULL, 'Publisher ID', 1),
(38, 115, 'creativeid', '[=CREATIVEID=]', NULL, NULL, 'Creative ID', 1),
(39, 115, 'mobtag', '[=MOBTAG=]', NULL, NULL, 'Click ID', 1),
(40, 115, 'campaignid', '[=CAMPAIGNID=]', NULL, NULL, 'Mobpartner campaign Name', 1),
(41, 115, 'actionid', '[=ACTIONID=]', NULL, NULL, 'Action ID', 1),
(42, 115, 'ip', '[=IP=]', NULL, NULL, 'IP Address', 1),
(43, 115, 'country', '[=COUNTRY=]', NULL, NULL, 'Country Code', 1),
(44, 117, 'idfa_raw', '${IDFA_RAW}', NULL, NULL, 'iOS IDFA', 1),
(45, 117, 'adcloud_userinfo', '${ADCLOUD_USERINFO}', NULL, NULL, 'User info', 1),
(46, 117, 'adcloud_clickinfo', '${ADCLOUD_CLICKINFO}', NULL, NULL, 'Click info', 1),
(47, 117, 'adslot_id', '${ADSLOT_ID}', NULL, NULL, 'Publisher ID', 1),
(48, 118, 'idfa', '{idfa}', NULL, NULL, 'iOS IDFA', 1),
(49, 118, 'idfv', '{idfv}', NULL, NULL, 'iOS IDFV', 1),
(50, 118, 'gaid', '{gaid}', NULL, NULL, 'Google Advertising ID', 1),
(51, 118, 'hdidfv', '{hdidfv}', NULL, NULL, 'HDIDFV', 1),
(52, 118, 'phid', '{phid}', NULL, NULL, 'PHID - Windows Phone 8 identifier', 1),
(53, 118, 'waid', '{waid}', NULL, NULL, 'Windows advertising ID - for Windows 8 desktop', 1),
(54, 118, 'sub_publisher', '{sub_publisher}', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(55, 118, 'creativeid', '{creativeID}', NULL, NULL, 'Creative ID', 1),
(56, 118, 'device_ip', '{device_IP}', NULL, NULL, 'IP Address', 1),
(57, 118, 'campaign_id', '{campaign_id}', NULL, NULL, 'Campaign ID', 1),
(58, 118, 'gift_type', '{gift_type}', NULL, NULL, 'Gift type', 1),
(59, 118, 'gift_amount', '{gift_amount}', NULL, NULL, 'Gift amount', 1),
(60, 118, 'platform_os', '{platform_os}', NULL, NULL, 'Device OS - ios, android, win (Windows 8 - desktop), winp (Windows Phone 8)', 1),
(61, 118, 'target_pid', '{target_PID}', NULL, NULL, 'Product ID', 1),
(62, 120, 'ios_ifa', '{ios_ifa}', NULL, NULL, 'iOS Identifier for Advertising', 1),
(63, 120, 'google_aid', '{google_aid}', NULL, NULL, 'Google AID', 1),
(64, 120, 'clickid', '{clickid}', NULL, NULL, 'ClickId to ba passed in post back', 1),
(65, 120, 'aff_id_cm', '{aff_id_cm}', NULL, NULL, 'The ID of the publisher.', 1),
(66, 122, 'transaction_id', '{transaction_id}', NULL, NULL, 'ID of the transaction for network. Don''t get confused with an ID an affiliate passes into aff_sub', 1),
(67, 122, 'offer_id', '{offer_id}', NULL, NULL, 'ID of offer', 1),
(68, 122, 'device_brand', '{device_brand}', NULL, NULL, 'The brand name of the mobile device (example: Apple)', 1),
(69, 122, 'device_model', '{device_model}', NULL, NULL, 'Model of the mobile device (example: iPhone)', 1),
(70, 122, 'device_os', '{device_os}', NULL, NULL, 'operating system of the device (example: iOS)', 1),
(71, 122, 'device_os_version', '{device_os_version}', NULL, NULL, 'The numerical version of the device operating system (example: 4.3.2)', 1),
(72, 122, 'ios_ifa', '{ios_ifa}', NULL, NULL, 'Apples advertiser identifier with iOS 6+.', 1),
(73, 122, 'google_aid', '{google_aid}', NULL, NULL, 'The Google advertiser ID', 1),
(74, 122, 'mac_address', '{mac_address}', NULL, NULL, 'The MAC address of the phones wifi adapter formatted as upper case with colons. AA:BB:CC:DD:EE:FF', 1),
(75, 122, 'odin', '{odin}', NULL, NULL, 'The ODIN of the device which is the the MAC address of the phone''s wifi adapter in a binary array and then hashed with SHA1 algorithm', 1),
(76, 122, 'open_udid', '{open_udid}', NULL, NULL, 'The OpenUDID of the device', 1),
(77, 122, 'unid', '{unid}', NULL, NULL, 'The unid is not a specific device identifier, but a catch all for all of the above unique identifiers', 1),
(78, 122, 'user_id', '{user_id}', NULL, NULL, 'ID generated by app developer (advertiser) that is the same ID of the user in their system', 1),
(79, 122, 'source', '{source}', NULL, NULL, 'Source value specified in the tracking link', 1),
(80, 122, 'aff_sub', '{aff_sub}', NULL, NULL, 'Affiliate sub specified in the tracking link', 1),
(81, 122, 'aff_sub2', '{aff_sub2}', NULL, NULL, 'The ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(82, 122, 'aff_sub3', '{aff_sub3}', NULL, NULL, 'The ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(83, 122, 'aff_sub4', '{aff_sub4}', NULL, NULL, 'The ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(84, 122, 'aff_sub5', '{aff_sub5}', NULL, NULL, 'The ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(85, 122, 'ip', '{ip}', NULL, NULL, 'IP address that made the conversion request', 1),
(86, 124, 'appleidfa', '[[AppleIdfa]]', NULL, NULL, 'iOS IDFA', 1),
(87, 124, 'gaid', '[[GAID]]', NULL, NULL, 'Google Advertising ID', 1),
(88, 124, 'sub', '[[Sub-Id]]', NULL, NULL, 'Click ID', 1),
(89, 124, 'ip', '[[IP]]', NULL, NULL, 'IP Address', 1),
(90, 124, 'appid', '[[AppId]]', NULL, NULL, 'Sub publisher', 1),
(91, 126, 'transaction_id', '{transaction_id}', NULL, NULL, 'ID of the transaction for network. Don''t get confused with an ID an affiliate passes into aff_sub', 1),
(92, 126, 'affiliate_id', '{affiliate_id}', NULL, NULL, 'Publisher ID', 1),
(93, 126, 'offer_id', '{offer_id}', NULL, NULL, 'ID of offer', 1),
(94, 126, 'aff_sub2', '{aff_sub2}', NULL, NULL, 'Site ID', 1),
(95, 126, 'country_code', '{country_code}', NULL, NULL, 'Two-letter ISO country code of user (ex. US)', 1),
(96, 126, 'ip', '{ip}', NULL, NULL, 'IP address that made the conversion request', 1),
(97, 128, 'sas_deviceid', '[sas_deviceId]', NULL, NULL, 'Android Advertiser ID', 1),
(98, 128, 'sas_deviceid', '[sas_deviceId]', NULL, NULL, 'iOS Advertiser ID', 1),
(99, 128, 'siteid', '[siteID]', NULL, NULL, 'Publisher ID', 1),
(100, 13, 'ifa', '{ifa}', NULL, NULL, 'iOS IDFA/ Google Advertising ID', 1),
(101, 13, 'source_game_id', '{source_game_id}', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(102, 13, 'game_id', '{game_id}', NULL, NULL, 'the Applifier game ID', 1),
(103, 13, 'country_code', '{country_code}', NULL, NULL, 'the 2 letter country code', 1),
(104, 13, 'creative_pack', '{creative_pack}', NULL, NULL, 'Creative', 1),
(105, 130, 'sha1_idfa', '{sha1_idfa}', NULL, NULL, 'The iOS Advertiser ID hashed (Preferable)', 1),
(106, 130, 'idfa', '{idfa}', NULL, NULL, 'The iOS Advertiser', 1),
(107, 130, 'sha1_gaid', '{sha1_gaid}', NULL, NULL, 'The Android Advertiser ID hashed (Preferable)', 1),
(108, 130, 'gaid', '{gaid}', NULL, NULL, 'The Android Advertiser ID', 1),
(109, 130, 'clickid', '{clickid}', NULL, NULL, 'internal click ID to be passed at post back', 1),
(110, 130, 'campaign_id', '{{campaign_id}}', NULL, NULL, 'Campaign ID', 1),
(111, 130, 'banner_id', '{{banner_id}}', NULL, NULL, 'Banner ID', 1),
(112, 130, 'gender', '{{gender}}', NULL, NULL, 'Gender', 1),
(113, 130, 'age', '{{age}}', NULL, NULL, 'Age', 1),
(114, 132, 'idfa', '{idfa}', NULL, NULL, 'iOS IDFA', 1),
(115, 132, 'gaid', '{gaid}', NULL, NULL, 'Google Advertising ID', 1),
(116, 134, 'cookieid', '%COOKIEID', NULL, NULL, 'internal click ID to be passed at post back', 1),
(117, 134, 'hash_code', '%HASH_CODE', NULL, NULL, 'campaign depending param to be passed at post back', 1),
(118, 136, 'ios_ifa', '{ios_ifa}', NULL, NULL, 'iOS Advertiser ID', 1),
(119, 136, 'google_id', '{google_id}', NULL, NULL, 'Google Advertiser ID', 1),
(120, 136, 'pub_id', '{pub_id}', NULL, NULL, 'Publisher ID', 1),
(121, 136, 'click_id', '{CLICK_ID}', NULL, NULL, 'Click ID (to pass @ post back)', 1),
(122, 136, 'country_code', '{country_code}', NULL, NULL, 'Country ISO code', 1),
(123, 136, 'ip', '{IP}', NULL, NULL, 'IP Address', 1),
(124, 138, 'sas_deviceid', '[sas_deviceId]', NULL, NULL, 'iOS/Android device id', 1),
(125, 138, 'sas_siteid', '[sas_siteId]', NULL, NULL, 'Sub publisher', 1),
(126, 140, 'idfa', '{idfa}', NULL, NULL, 'iOS IDFA', 1),
(127, 140, 'gaid', '{gaid}', NULL, NULL, 'Google Advertising ID', 1),
(128, 140, 'clickid', '{clickid}', NULL, NULL, 'Click ID', 1),
(129, 140, 'placementid', '{placementID}', NULL, NULL, 'Placement ID', 1),
(130, 140, 'refid', '{refid}', NULL, NULL, 'Sub publisher', 1),
(131, 142, 'advertising_id', '{advertising_id}', NULL, NULL, 'Android Advertiser ID', 1),
(132, 142, 'ifa', '{ifa}', NULL, NULL, 'iOS Advertiser ID', 1),
(133, 142, 'clickid', '{clickid}', NULL, NULL, 'Click id to send in post back', 1),
(134, 142, 'ad_id', '{ad_id}', NULL, NULL, 'Creative', 1),
(135, 142, 'publisher_id', '{publisher_id}', NULL, NULL, 'Publisher ID', 1),
(136, 144, 'idfa', '%IDFA%', NULL, NULL, 'iOS IDFA/ Google Advertising ID', 1),
(137, 144, 'lat', '%LAT%', NULL, NULL, 'Limit Ad Tracking (If the ''Limit Ad Tracking'' option is enabled, lat=1, otherwise, lat=0)', 1),
(138, 144, 'suid', '{suid}', NULL, NULL, 'Unique session ID', 1),
(139, 146, 'subid', '${SUBID}', NULL, NULL, 'Click ID', 1),
(140, 146, 'zoneid', '{zoneid}', NULL, NULL, 'Sub publisher', 1),
(141, 148, 'ios_ifa', '{ios_ifa}', NULL, NULL, 'The iOS Advertiser ID', 1),
(142, 148, 'google_aid', '{google_aid} ', NULL, NULL, 'The Android Advertiser ID', 1),
(143, 148, 'sub1', '{sub1}', NULL, NULL, 'Click id to be sent in post back', 1),
(144, 148, 'subid', '{SUBID}', NULL, NULL, 'Sub publisher', 1),
(145, 15, 'transaction_id', '{transaction_id}', NULL, NULL, 'Click ID', 1),
(146, 15, 'ios_ifa', '{ios_ifa}', NULL, NULL, 'iOS IDFA', 1),
(147, 15, 'android_id', '{android_id}', NULL, NULL, 'Android ID/ Google Advertising ID', 1),
(148, 15, 'affiliate_id', '{affiliate_id}', NULL, NULL, 'The ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(149, 15, 'source', '{source}', NULL, NULL, 'Sub ID', 1),
(150, 150, 'pid', '[pid]', NULL, NULL, 'iOS IDFA/ Google Advertising Id', 1),
(151, 150, 'shares', '[shares]', NULL, NULL, 'The ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(152, 152, 'sas_deviceid', '[sas_deviceId]', NULL, NULL, 'iOS IDFA/ Google Advertising Id', 1),
(153, 156, 'adid', '{adid}', NULL, NULL, 'Google Advertising ID', 1),
(154, 156, 'idfa', '{idfa}', NULL, NULL, 'iOS Advertiser ID', 1),
(155, 156, 'data', '{data}', NULL, NULL, 'Click id to send in post back', 1),
(156, 156, 'targetingid', '{targetingId}', NULL, NULL, 'Publisher ID', 1),
(157, 158, 'clickidmacro', '{CLICKIDMACRO}', NULL, NULL, 'Click id to send in post back', 1),
(158, 158, 'sub_publisher', '{sub_publisher}', NULL, NULL, 'Publisher ID', 1),
(159, 160, 'user_id', '{user_id}', NULL, NULL, 'iOS IDFA', 1),
(160, 160, 'startapp_advertising_id', '{startapp_advertising_id}', NULL, NULL, 'Google Advertising ID', 1),
(161, 160, 'startapp_app_id', '{startapp_app_id}', NULL, NULL, 'The App ID of the publishing app from which every click came', 1),
(162, 160, 'startapp_dev_id', '{startapp_dev_id}', NULL, NULL, 'The Publisher ID of the publishing app from which every click came', 1),
(163, 160, 'creative_id', '{creative_id}', NULL, NULL, 'Creative ID', 1),
(164, 160, 'startapp_country', '{startapp_country}', NULL, NULL, 'Country', 1),
(165, 160, 'startapp_click_id_placeholder', '{startapp_click_id_placeholder}', NULL, NULL, 'Click ID', 1),
(166, 164, 'ios_ifa', '{ios_ifa}', NULL, NULL, 'iOS AID', 1),
(167, 164, 'google_aid', '{google_aid}', NULL, NULL, 'Google AID', 1),
(168, 164, 'source', '{source}', NULL, NULL, 'Sub Publisher', 1),
(169, 164, 'aff_sub', '{aff_sub}', NULL, NULL, 'Site', 1),
(170, 164, 'transaction_id', '{transaction_id}', NULL, NULL, 'Click ID to be passed in post back', 1),
(171, 166, 'device_id', '{device_id}', NULL, NULL, 'iOS IDFA', 1),
(172, 166, 'affiliate_id', '{affiliate_id}', NULL, NULL, 'Sub publisher', 1),
(173, 166, 'transaction_id', '{transaction_id}', NULL, NULL, 'Session ID', 1),
(174, 168, 'sas_deviceid', '[sas_deviceId]', NULL, NULL, 'The iOS/Android Advertiser ID', 1),
(175, 17, 'pattern', '%%PATTERN:idfa%%', NULL, NULL, 'iOS IDFA', 1),
(176, 17, 'pattern', '%%PATTERN:adid%%', NULL, NULL, 'Google Advertising Id', 1),
(177, 17, 'pattern', '%%PATTERN:game%%', NULL, NULL, 'The ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(178, 170, 'googleaid', 'GOOGLEAID', NULL, NULL, 'Google AID', 1),
(179, 170, 'iosifa', 'IOSIFA', NULL, NULL, 'IOS AID', 1),
(180, 170, 'idprovider', 'IDPROVIDER', NULL, NULL, 'Publisher ID', 1),
(181, 170, 'subid1', 'SUBID1', NULL, NULL, 'Sub publisher ID', 1),
(182, 170, 'idclick', 'IDCLICK', NULL, NULL, 'Click ID to be passed in post back', 1),
(183, 172, 'ams2s', '*ams2s*', NULL, NULL, 'Click ID', 1),
(184, 174, 'ios_ifa', '{ios_ifa}', NULL, NULL, 'iOS Advertiser ID', 1),
(185, 174, 'device_id', '{device_id}', NULL, NULL, 'Android Advertiser ID', 1),
(186, 174, 'affiliate_id', '{affiliate_id}', NULL, NULL, 'Sub Publisher', 1),
(187, 176, 'sub_publisher', '{sub_publisher}', NULL, NULL, 'The ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(188, 178, 'ios_ifa', '{ios_ifa}', NULL, NULL, 'iOS Advertising ID', 1),
(189, 178, 'google_aid', '{google_aid}', NULL, NULL, 'Google Advertising ID', 1),
(190, 178, 'ref_id', '{ref_id}', NULL, NULL, 'Click ID', 1),
(191, 178, 'sub_campaign', '{sub_campaign}', NULL, NULL, 'Internal campaign ID', 1),
(192, 180, 'affiliate_id', '{affiliate_id}', NULL, NULL, 'Publisher ID', 1),
(193, 180, 'banner', '{banner}', NULL, NULL, 'Creative', 1),
(194, 180, 'offer_id', '{offer_id}', NULL, NULL, 'Offer (to pass @ post back)', 1),
(195, 180, 'transaction_id', '{transaction_id}', NULL, NULL, 'Click (to pass @ post back)', 1),
(196, 182, 'ios_ifa', '{ios_ifa}', NULL, NULL, 'iOS IDFA', 1),
(197, 182, 'google_advertising_id', '{google_advertising_id}', NULL, NULL, 'Google Advertising ID', 1),
(198, 182, 'affiliate_id', '{affiliate_id}', NULL, NULL, 'Sub publisher', 1),
(199, 182, 'transaction', '{transaction}', NULL, NULL, 'Click ID', 1),
(200, 186, 'idfa', '{idfa}', NULL, NULL, 'iOS Advertiser ID', 1),
(201, 186, 'gaid', '{gaid}', NULL, NULL, 'Android Advertiser ID', 1),
(202, 186, 'sid', '{sid}', NULL, NULL, 'Publisher ID', 1),
(203, 186, 'tid', '{tid}', NULL, NULL, 'Click (to pass @ post back)', 1),
(204, 19, 'eudid', '%eudid!', NULL, NULL, 'IDFA/ SHA1 Hashed Android ID/ Android Advertising ID', 1),
(205, 19, 'ecid', '%ecid!', NULL, NULL, 'The ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(206, 19, 'cachebuster', '%%CACHEBUSTER%%', NULL, NULL, 'Cache Buster (generates a random number)', 1),
(207, 19, 'eaid', '%eaid!', NULL, NULL, 'Ad Group ID', 1),
(208, 190, 's2sid', '%S2SID%', NULL, NULL, 'Transaction ID', 1),
(209, 190, 'poolid', '%POOLID%', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(210, 190, 'countryid', '%COUNTRYID%', NULL, NULL, 'Country ID', 1),
(211, 192, 'affiliate_id', '[affiliate_id]', NULL, NULL, 'Sub publisher', 1),
(212, 192, 'transaction_id', '[transaction_id]', NULL, NULL, 'Click ID', 1),
(213, 194, 'ios_ifa', '{ios_ifa}', NULL, NULL, 'iOS Advertising ID', 1),
(214, 194, 'google_aid', '{google_aid}', NULL, NULL, 'Google Advertising ID', 1),
(215, 194, 'affiliate_id', '{affiliate_id}{source}', NULL, NULL, 'Sub publisher', 1),
(216, 194, 'aff_sub5', '{aff_sub5}', NULL, NULL, 'Creative', 1),
(217, 196, 'device_id', '{device_id}', NULL, NULL, 'iOS/Google Advertising ID', 1),
(218, 196, 'ad_delivery_token', '{ad_delivery_token}', NULL, NULL, 'Unique ID assigned to the ad creative file and click. To be sent in post back.', 1),
(219, 196, 'app_key', '{app_key}', NULL, NULL, 'Sub publisher', 1),
(220, 196, 'creative_token', '{creative_token}', NULL, NULL, 'Creative', 1),
(221, 198, 'click_id', '#click_id#', NULL, NULL, 'Click ID', 1),
(222, 198, 'wm_id', '#wm_id#', NULL, NULL, 'Publisher ID', 1),
(223, 200, 'offer_id', '{offer_id}', NULL, NULL, 'Campaign title id (ex Asphalt 8, Despicable Me, Ice Age Village)', 1),
(224, 200, 'aff_id', '{aff_id}', NULL, NULL, 'Sub Publisher', 1),
(225, 200, 'transaction_id', '{transaction_id}', NULL, NULL, 'Click ID', 1),
(226, 200, 'google_aid', '{google_aid}', NULL, NULL, 'Google advertising id', 1),
(227, 202, 'clickid', '{clickid}', NULL, NULL, 'Click ID', 1),
(228, 202, 'action_id', '{action_id}', NULL, NULL, 'Lead ID', 1),
(229, 202, 'pid', '{pid}', NULL, NULL, 'Sub publisher', 1),
(230, 202, 'sub4', '{sub4}', NULL, NULL, 'Creative', 1),
(231, 204, 'aff_sub', '{aff_sub}', NULL, NULL, 'Sub publisher', 1),
(232, 208, 'idfa', '{idfa}', NULL, NULL, 'iOS Advertising ID', 1),
(233, 208, 'android_id', '{android_id}', NULL, NULL, 'Google Advertising ID', 1),
(234, 208, 'uid', '{uid}', NULL, NULL, 'Clickky''s unique click ID for each click Mandatory', 1),
(235, 21, 'tapjoy_generic_source', 'TAPJOY_GENERIC_SOURCE', NULL, NULL, 'The ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(236, 21, 'tapjoy_restored_raw_advertising_id', 'TAPJOY_RESTORED_RAW_ADVERTISING_ID', NULL, NULL, 'Raw, unhashed IDFA/ Google Advertising ID', 1),
(237, 21, 'ip_address', '[ip_address]', NULL, NULL, 'IP address', 1),
(238, 214, 'idfa', '{idfa}', NULL, NULL, 'iOS Advertising ID', 1),
(239, 214, 'gaid', '{gaid}', NULL, NULL, 'Google Advertising ID', 1),
(240, 214, 'suid', '{suid}', NULL, NULL, '', 1),
(241, 214, 'sad', '{sad}', NULL, NULL, '', 1),
(242, 216, 'idfa', '{IDFA}', NULL, NULL, 'iOS Advertising ID', 1),
(243, 216, 'android_aid', '{ANDROID_AID}', NULL, NULL, 'Google Advertising ID', 1),
(244, 216, 'offer', '{OFFER}', NULL, NULL, 'Offer name', 1),
(245, 216, 'campaignid', '{CAMPAIGNID}', NULL, NULL, 'Placement/Source ID', 1),
(246, 216, 'sid', '{SID}', NULL, NULL, 'Conversion value', 1),
(247, 218, 'cad', '$CAD[device_ifa]', NULL, NULL, 'iOS/Google Advertising ID', 1),
(248, 218, 'creative_id', '${CREATIVE_ID}', NULL, NULL, 'Creative', 1),
(249, 218, 'publisher_id', '${PUBLISHER_ID}', NULL, NULL, 'Sub Publisher', 1),
(250, 218, 'click_id', '${CLICK_ID}', NULL, NULL, 'Click ID', 1),
(251, 218, 'country', '${COUNTRY}', NULL, NULL, 'Country code', 1),
(252, 218, 'ip', '${IP}', NULL, NULL, 'IP address', 1),
(253, 218, 'user_agent_enc', '${USER_AGENT_ENC}', NULL, NULL, 'User agent', 1),
(254, 218, 'user_language', '${USER_LANGUAGE}', NULL, NULL, 'Language', 1),
(255, 220, 'ios_ifa', '{ios_ifa}', NULL, NULL, 'iOS Advertising ID', 1),
(256, 220, 'google_aid', '{google_aid}', NULL, NULL, 'Google Advertising ID', 1),
(257, 220, 'aff_sub5', '{aff_sub5}', NULL, NULL, '', 1),
(258, 220, 'transaction_id', '{transaction_id}', NULL, NULL, 'Click ID', 1),
(259, 220, 'region_code', '{region_code}', NULL, NULL, 'Region code', 1),
(260, 220, 'country_code', '{country_code}', NULL, NULL, 'Country code', 1),
(261, 220, 'ip', '{ip}', NULL, NULL, 'IP address', 1),
(262, 220, 'user_agent', '{user_agent}', NULL, NULL, 'User agent', 1),
(263, 220, 'affiliate_id', '{affiliate_id}', NULL, NULL, 'Sub publisher', 1),
(264, 222, 'offer_file_id', '{offer_file_id}', NULL, NULL, 'Creative', 1),
(265, 222, 'affiliate_id', '{affiliate_id}', NULL, NULL, 'Sub Publisher', 1),
(266, 222, 'source', '{source}', NULL, NULL, 'publisher source', 1),
(267, 222, 'transaction_id', '{transaction_id}', NULL, NULL, 'click id (to be passed in post back)', 1),
(268, 224, 'ios_ifa', '{ios_ifa}', NULL, NULL, 'iOS IDFA', 1),
(269, 224, 'affiliate_id', '{affiliate_id}', NULL, NULL, 'Sub publisher', 1),
(270, 224, 'transaction_id', '{transaction_id}', NULL, NULL, 'Click ID', 1),
(271, 23, 'ifa', '{{{ifa}}}', NULL, NULL, 'iOS IDFA/ Windows Advertising ID/ Google Advertising ID (see note below)', 1),
(272, 23, 'aaid', '{{{aaid}}}', NULL, NULL, 'Google Advertising ID', 1),
(273, 23, 'id', '{{{id}}}', NULL, NULL, 'Vungle event identifier', 1),
(274, 23, 'app_id', '{{{app_id}}}', NULL, NULL, 'Vungle application identifier', 1),
(275, 23, 'campaignid', '{{{campaignId}}}', NULL, NULL, 'Vungle campaign identifier', 1),
(276, 23, 'creative', '{{{creative}}}', NULL, NULL, 'Creative name', 1),
(277, 23, 'site_id', '{{{site_id}}}', NULL, NULL, 'The ID of the app where the ad served', 1),
(278, 23, 'site_name', '{{{site_name}}}', NULL, NULL, 'The name of the app where the ad served', 1),
(279, 23, 'country', '{{{country}}}', NULL, NULL, 'Country Code', 1),
(280, 23, 'country_name', '{{{country_name}}}', NULL, NULL, 'Country Name', 1),
(281, 23, 'country_adx', '{{{country_adx}}}', NULL, NULL, 'Other Identifier', 1),
(282, 23, 'device_ios', '{{{device_ios}}}', NULL, NULL, 'For iOS (iPhone, iPad etc.)', 1),
(283, 23, 'device_android', '{{{device_android}}}', NULL, NULL, 'For Android (phone, tablet etc.)', 1),
(284, 23, 'timestamp', '{{{timestamp}}}', NULL, NULL, 'Timestamp', 1),
(285, 230, 'ios_ifa', '{ios_ifa}', NULL, NULL, 'iOS IDFA', 1),
(286, 230, 'google_aid', '{google_aid}', NULL, NULL, 'Google Advertising ID', 1),
(287, 230, 'sub_campaign', '{sub_campaign}', NULL, NULL, 'The ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(288, 230, 'ref_id', '{ref_id}', NULL, NULL, 'Wizzo unique user ID', 1),
(289, 232, 'idfa', '[=idfa=]', NULL, NULL, 'iOS IDFA', 1),
(290, 232, 'gaid', '[=gaid=]', NULL, NULL, 'Google Advertising ID', 1),
(291, 232, 'afid', '[=AFID=]', NULL, NULL, 'The ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(292, 232, 'sid', '[=SID=]', NULL, NULL, 'Creative', 1),
(293, 232, 'clickid', '[=ClickID=]', NULL, NULL, 'Click ID', 1),
(294, 234, 'idfa_md5', '{idfa_md5}', NULL, NULL, 'iOS IDFA (MD5 encrypted)', 1),
(295, 234, 'ip', '{ip}', NULL, NULL, 'IP Address', 1),
(296, 234, 'country_code', '{country_code}', NULL, NULL, 'Country Code (for instance, 0086 for China)', 1),
(297, 234, 'sub_publisher', '{sub_publisher}', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(298, 234, 'callback_param', '{callback_param}', NULL, NULL, 'Callback parameter', 1),
(299, 238, 'idfa', '{idfa}', NULL, NULL, 'iOS IDFA', 1),
(300, 238, 'gaid', '{gaid}', NULL, NULL, 'Google Advertising ID', 1),
(301, 238, 'sub_publisher', '{sub_publisher}', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(302, 238, 'user_id', '{user_id}', NULL, NULL, 'User ID', 1),
(303, 238, 'content_id', '{content_id}', NULL, NULL, 'Content ID', 1),
(304, 240, 'idfa', '{idfa}', NULL, NULL, 'iOS IDFA', 1),
(305, 240, 'ip', '{ip}', NULL, NULL, 'IP Address', 1),
(306, 240, 'country_code', '{country_code}', NULL, NULL, 'Country Code (for instance, 86 for China)', 1),
(307, 240, 'sub_publisher', '{sub_publisher}', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(308, 242, 'gaid', '{gaid}', NULL, NULL, 'Google Advertising ID', 1),
(309, 242, 'mcid', '{mcid}', NULL, NULL, 'Mcid', 1),
(310, 244, 'swat', '[SWAT click data]', NULL, NULL, 'Session ID', 1),
(311, 246, 'idfa', '{idfa}', NULL, NULL, 'iOS IDFA', 1),
(312, 246, 'gps_adid', '{gps_adid}', NULL, NULL, 'Google Advertising ID', 1),
(313, 246, 'aff_sub2', '{aff_sub2}', NULL, NULL, 'Sub publisher', 1),
(314, 246, 'aff_sub4', '{aff_sub4}', NULL, NULL, 'Creative', 1),
(315, 246, 'transaction_id', '{transaction_id}', NULL, NULL, 'Transaction ID', 1),
(316, 25, 'affiliate_id', '{affiliate_id}', NULL, NULL, 'The ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(317, 25, 'country_code', '{country_code}', NULL, NULL, 'Country Code', 1),
(318, 25, 'ios_ifa', '{ios_ifa}', NULL, NULL, 'iOS IDFA', 1),
(319, 25, 'unid', '{unid}', NULL, NULL, 'Google Advertising ID', 1),
(320, 25, 'ip', '{IP}', NULL, NULL, 'IP address', 1),
(321, 25, 'transaction_id', '{transaction_id}', NULL, NULL, 'Unique click ID from Applift', 1),
(322, 252, 'sub8', '{sub8}', NULL, NULL, 'iOS IDFA', 1),
(323, 252, 'sub7', '{sub7}', NULL, NULL, 'Google Advertising ID', 1),
(324, 252, 'affiliate_id', '{affiliate_id}', NULL, NULL, 'Sub publisher', 1),
(325, 252, 'sub6', '{sub6}', NULL, NULL, 'Creative', 1),
(326, 252, 'clickid', '{clickid}', NULL, NULL, 'Click ID', 1),
(327, 254, 'adid', '{adid}', NULL, NULL, 'Google Advertising ID', 1),
(328, 254, 'idfa', '{idfa}', NULL, NULL, 'iOS Advertising ID', 1),
(329, 254, 'targetingid', '{targetingId}', NULL, NULL, 'Sub publisher', 1),
(330, 254, 'network', '{network}', NULL, NULL, 'Optional, always populated with pub network name.', 1),
(331, 254, 'platform', '{platform}', NULL, NULL, 'Optional, one of the following: ''ANDROID'', ''IPHONE'', ''IPAD''.', 1),
(332, 254, 'appid', '{appId}', NULL, NULL, 'Optional, unique advertiser application ID.', 1),
(333, 256, 'ios_ifa', '{ios_ifa}', NULL, NULL, 'iOS IDFA', 1),
(334, 256, 'android_id', '{android_id}', NULL, NULL, 'Google Advertising ID', 1),
(335, 256, 'affiliate_id', '{affiliate_id}', NULL, NULL, 'Sub publisher', 1),
(336, 256, 'aff_sub', '{aff_sub}', NULL, NULL, 'Sub-sub publisher', 1),
(337, 256, 'source', '{source}', NULL, NULL, 'Creative', 1),
(338, 256, 'transaction_id', '{transaction_id}', NULL, NULL, 'Transaction ID', 1),
(339, 258, 'uid_deviceid', '{uid_deviceid}', NULL, NULL, 'Google Advertising ID / iOS IDFA', 1),
(340, 258, 'campaign', '{campaign}', NULL, NULL, 'Go2mobi campaign id', 1),
(341, 258, 'pln', '{pln}', NULL, NULL, 'Placement name', 1),
(342, 258, 'plid', '{plid}', NULL, NULL, 'Placement ID', 1),
(343, 258, 'crid', '{crid}', NULL, NULL, 'Creative ID', 1),
(344, 258, 'country', '{country}', NULL, NULL, 'Country', 1),
(345, 258, 'clickid', '{clickid}', NULL, NULL, 'Click ID', 1),
(346, 262, 'ios_ifa', '{ios_ifa}', NULL, NULL, 'iOS IDFA', 1),
(347, 262, 'google_aid', '{google_aid}', NULL, NULL, 'Google Advertising ID', 1),
(348, 262, 'xapnt17x', 'xapnt17x', NULL, NULL, 'Sub publisher', 1),
(349, 262, 'xapnt1x', 'xapnt1x', NULL, NULL, 'Click ID', 1),
(350, 266, 'ifa', '{IFA}', NULL, NULL, 'iOS IDFA/ Google Advertising ID', 1),
(351, 266, 'appid', '{APPID}', NULL, NULL, 'Sub publisher', 1),
(352, 266, 'creativeid', '{CREATIVEID}', NULL, NULL, 'Creative', 1),
(353, 266, 'event', '{EVENT}', NULL, NULL, 'The event name', 1),
(354, 266, 'distinctid', '{DISTINCTID}', NULL, NULL, 'Transaction ID', 1),
(355, 266, 'creativename', '{CREATIVENAME}', NULL, NULL, 'Creative name', 1),
(356, 266, 'creativeversion', '{CREATIVEVERSION}', NULL, NULL, 'Creative version', 1),
(357, 266, 'appadvertised', '{APPADVERTISED}', NULL, NULL, 'The name of the advertised app', 1),
(358, 266, 'os', '{OS}', NULL, NULL, 'Device OS', 1),
(359, 266, 'target', '{TARGET}', NULL, NULL, 'Tracking target', 1),
(360, 266, 'mp', '{MP}', NULL, NULL, 'Mixpanel integration', 1),
(361, 268, 'clickid', '[ClickID]', NULL, NULL, 'Publisher''s click ID', 1),
(362, 268, 'deviceid', '[DeviceID]', NULL, NULL, 'iOS Advertising ID', 1),
(363, 268, 'deviceid', '[DeviceID]', NULL, NULL, 'Google Advertising ID', 1),
(364, 268, 'pub', '[PUB]', NULL, NULL, 'Sub publisher', 1),
(365, 268, 'kid', '[KID]', NULL, NULL, '', 1),
(366, 268, 'bid', '[BID]', NULL, NULL, '', 1),
(367, 268, 'tid', '[TID]', NULL, NULL, '', 1),
(368, 268, 'sid', '[SID]', NULL, NULL, '', 1),
(369, 268, 'wp_id', '[WP_ID]', NULL, NULL, '', 1),
(370, 268, 'uid', '[UID]', NULL, NULL, '', 1),
(371, 27, 'udid', '%(UDID)s', NULL, NULL, 'IDFA/ Google Ad ID', 1),
(372, 27, 'pub_id', '%(PUB_ID)s', NULL, NULL, 'The ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(373, 27, 'ip', '%(IP)s', NULL, NULL, 'IP Address', 1),
(374, 27, 'click_id', '%(CLICK_ID)s', NULL, NULL, 'Click ID from Swelen', 1),
(375, 272, 'device_apple_ida', '${DEVICE_APPLE_IDA}', NULL, NULL, 'iOS IDFA', 1),
(376, 272, 'device_aaid', '${DEVICE_AAID}', NULL, NULL, 'Google Advertising ID', 1),
(377, 272, 'device_win_id', '${DEVICE_WIN_ID}', NULL, NULL, 'Windows Advertising ID', 1),
(378, 272, 'ext_app_id', '${EXT_APP_ID}', NULL, NULL, 'Sub publisher', 1),
(379, 272, 'ssp_data', '${SSP_DATA}', NULL, NULL, 'SSP data', 1),
(380, 274, 'aff_sub', '{aff_sub}', NULL, NULL, 'Sub publisher', 1),
(381, 274, 'affiliate_id', '{affiliate_id}', NULL, NULL, 'Affiliate ID', 1),
(382, 274, 'transaction_id', 'TRANSACTION_ID', NULL, NULL, 'Transaction ID', 1),
(383, 276, 'iosidfa', '##IOSIDFA##', NULL, NULL, 'iOS IDFA', 1),
(384, 276, 'gaid', '##GAID##', NULL, NULL, 'Google Advertising ID', 1),
(385, 276, 'publisherid', '##PUBLISHERID##', NULL, NULL, 'Sub publisher', 1),
(386, 276, 'creativeid', '##CREATIVEID##', NULL, NULL, 'Creative', 1),
(387, 276, 'clickid', '##CLICKID##', NULL, NULL, 'Click ID', 1),
(388, 278, 'idfa', '{idfa}', NULL, NULL, 'iOS IDFA', 1),
(389, 278, 'gaid', '{gaid}', NULL, NULL, 'Google Advertising Id', 1),
(390, 280, 'sas_deviceid', '[sas_deviceId]', NULL, NULL, 'iOS IDFA/ Google Advertising ID', 1),
(391, 280, 'timestamp', '[timestamp]', NULL, NULL, 'CacheBuster', 1),
(392, 282, 'reqid', '#reqid#', NULL, NULL, 'Click ID', 1),
(393, 282, 's1', '#s1#', NULL, NULL, 'Site ID', 1),
(394, 282, 's2', '#s2#', NULL, NULL, 'Media source', 1),
(395, 284, 'ios_ifa', '{ios_ifa}', NULL, NULL, 'iOS IDFA', 1),
(396, 284, 'google_aid', '{google_aid}', NULL, NULL, 'Google Advertising ID', 1),
(397, 284, 'transaction_id', '{transaction_id}', NULL, NULL, 'Click ID', 1),
(398, 284, 'publisher_id', '{publisher_id}', NULL, NULL, 'Sub publisher', 1),
(399, 284, 'file_name', '{file_name}', NULL, NULL, 'Creative', 1),
(400, 29, 'idfa', '%idfa%', NULL, NULL, 'iOS IDFA', 1),
(401, 29, 'gaid', '%gaid%', NULL, NULL, 'Android ID', 1),
(402, 29, 'pubid', '%pubid%', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(403, 29, 'iso2', '%iso2%', NULL, NULL, 'Country ISO Code', 1),
(404, 29, 'udid', '%udid%', NULL, NULL, 'Device ID (iOS)', 1),
(405, 29, 'deviceid', '%deviceid%', NULL, NULL, 'Device ID (Android)', 1),
(406, 29, 'tp_sid', '%tp_sid%', NULL, NULL, 'Click ID', 1),
(407, 290, 'source_id', '{source_id}', NULL, NULL, 'Sub publisher', 1),
(408, 290, 'token', '{token}', NULL, NULL, 'Token (to pass @ post back)', 1),
(409, 296, 'advertising_id', '{{ADVERTISING_ID}}', NULL, NULL, 'iOS Advertising ID', 1),
(410, 296, 'app_id', '{{APP_ID}}', NULL, NULL, 'Sub publisher', 1),
(411, 298, 'your_source', '{your_source}', NULL, NULL, 'Sub publisher', 1),
(412, 3, 'ida', '$IDA', NULL, NULL, 'Apple ID for Advertisers. Example: 736C3D8E-6A4B-373E-718B-DE700561CFAD', 1),
(413, 3, 'gpid', '$GPID', NULL, NULL, 'Google Advertising ID', 1),
(414, 3, 'imp_id', '$IMP_ID', NULL, NULL, 'Unique click ID - this may be used as a cachebuster, and may be returned to InMobi by third-party conversion trackers to report a conversion. This will be of a format like this: 83f47f85-3c3c-4beb-a42e-b608b97a2c40', 1),
(415, 3, 'imp_ts', '$IMP_TS', NULL, NULL, 'Numeric timestamp, not recorded in logs', 1),
(416, 3, 'blinded_site_id', '$BLINDED_SITE_ID', NULL, NULL, 'Sub publisher macro - This would be an unique id for the site on which the ad would be shown', 1),
(417, 3, 'inmobi_gpmid', '{InMobi_GPMID}', NULL, NULL, 'Property ID (gpmid)', 1),
(418, 302, 'lr_idfa', '[LR_IDFA]', NULL, NULL, 'iOS IDFA/ Google Advertising ID', 1),
(419, 302, 'lr_idfa_flag', '[LR_IDFA_FLAG]', NULL, NULL, 'Boolean value, where 0 means that tracking is not enabled and 1 means that tracking is enabled', 1),
(420, 304, 'idfa', '{idfa}', NULL, NULL, 'iOS IDFA', 1),
(421, 304, 'gps_adid', '{gps_adid}', NULL, NULL, 'Google Advertising ID', 1),
(422, 304, 'affiliate_id', '{affiliate_id}', NULL, NULL, 'Sub publisher', 1),
(423, 304, 'aff_sub2', '{aff_sub2}', NULL, NULL, 'Creative', 1),
(424, 31, 'idfa', '{IDFA}', NULL, NULL, 'iOS IDFA', 1),
(425, 31, 'adid', '{ADID}', NULL, NULL, 'Google Ad ID', 1),
(426, 31, 'pub_id', '{PUB_ID}', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(427, 31, 'cc', '{CC}', NULL, NULL, 'Country Code', 1),
(428, 31, 'custom_parameter', '{CUSTOM_PARAMETER}', NULL, NULL, 'Click ID', 1),
(429, 33, 's5', '#s5#', NULL, NULL, 'Device Identifier (iOS IDFA / Google AID)', 1),
(430, 33, 'affid', '#affid#', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(431, 33, 'oid', '#oid#', NULL, NULL, 'Motive campaign ID', 1),
(432, 33, 'reqid', '#reqid#', NULL, NULL, 'Click ID', 1),
(433, 33, 'ip', '#ip#', NULL, NULL, 'IP Address', 1),
(434, 35, 'g', '{G.QUERY.ADID}', 'click', NULL, 'adid = The advertising ID (''in the clear''), a 32 char GUID', 1),
(435, 35, 'g', '{G.QUERY.MKT}', 'click', NULL, 'mkt = Internal MS data, a 6 char string (to be sent on the post-back)', 1),
(436, 35, 'g', '{G.QUERY.ASID}', 'click', NULL, 'bclid = Click ID; Internal MS data, a 32 char GUID (to be sent on the post-back)', 1),
(437, 35, 'g', '{G.QUERY.SAPPID}', 'click', NULL, 'sappid = Creative; Internal MS data, a 32 char GUID (to be sent on the post-back)', 1),
(438, 35, 'g', '{G.QUERY.PG}', 'click', NULL, 'pg = Sub publisher (site/ app ID); Internal MS data, a 20 char string (to be sent on the post-back)', 1),
(439, 35, 'g', '{G.QUERY.PID}', 'click', NULL, 'pid = Campaign ID; Internal MS data, a 32 char GUID (to be sent on the post-back)', 1),
(440, 35, 'g', '{G.QUERY.CID}', 'click', NULL, 'cid = Ad creative ID; Internal MS data, a 32 char GUID (to be sent on the post-back)', 1),
(441, 35, 'profile', '##(Profile.ADID{})##', 'impression', NULL, 'adid = The advertising ID (''in the clear''), a 32 char GUID', 1),
(442, 35, 'response', '##?Response(RID).Creative(CID).MARKET{}?##', 'impression', NULL, 'mkt = Internal MS data, a 6 char string (to be sent on the post-back)', 1),
(443, 35, 'request', '##(Request(RID).ASID)##', 'impression', NULL, 'bclid = Impression ID; Internal MS data, a 32 char GUID (to be sent on the post-back)', 1),
(444, 35, 'global', '##(Global.PN{})##', 'impression', NULL, 'sappid = Creative; Internal MS data, a 32 char GUID (to be sent on the post-back)', 1),
(445, 35, 'request', '##(Request(RID).PG{})##', 'impression', NULL, 'pg = Sub publisher (site/ app ID); Internal MS data, a 20 char string (to be sent on the post-back)', 1),
(446, 35, 'response', '##?Response(RID).Creative(CID).PID?##', 'impression', NULL, 'pid = Campaign ID; Internal MS data, a 32 char GUID (to be sent on the post-back)', 1),
(447, 35, 'response', '##?Response(RID).Creative(CID).CID?##', 'impression', NULL, 'cid = Ad creative ID; Internal MS data, a 32 char GUID (to be sent on the post-back)', 1),
(448, 37, 'deviceids', '{DeviceIds[IFA]}', NULL, NULL, 'iOS IDFA', 1),
(449, 37, 'deviceids', '{DeviceIds[AID]}', NULL, NULL, 'Google Advertising Id', 1),
(450, 37, 'cc', '{CC}', NULL, NULL, 'Country Code', 1),
(451, 37, 'ip', '{IP}', NULL, NULL, 'IP Address', 1),
(452, 37, 'dynamicparameter', '{DynamicParameter}', NULL, NULL, 'Click Id', 1),
(453, 37, 'applicationid', '{ApplicationId}', NULL, NULL, 'Sub publisher; The ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(454, 38, 'iosidfa', '#iOSIdFA#', NULL, NULL, 'The iOS Advertiser ID', 1),
(455, 38, 'androididfa', '#AndroidIDFA#', NULL, NULL, 'Google''s user specific, unique, resettable ID for advertising', 1),
(456, 38, 'publisherappid', '#PublisherAppId#', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(457, 38, 'osversion', '#OsVersion#', NULL, NULL, 'The device''s operating system version, e.g. iOS 7.0.1.', 1),
(458, 38, 'devicetype', '#DeviceType#', NULL, NULL, 'The hardware on which the user is viewing the ad. Examples include iPad, iPhone, Nexus 7, etc.', 1),
(459, 38, 'platformtype', '#PlatformType#', NULL, NULL, 'The platform type, either iOS or Android', 1),
(460, 38, 'clientip', '#ClientIp#', NULL, NULL, 'The IP address of the device (not the server making the calls)', 1),
(461, 38, 'countrycode', '#CountryCode#', NULL, NULL, 'A two letter country code in ISO 3166', 1),
(462, 38, 'unixtimestampinsec', '#UnixTimeStampInSec#', NULL, NULL, 'The Unix timestamp of the event', 1),
(463, 38, 'nonce', '#Nonce#', NULL, NULL, 'A number only used to identify this specific conversion', 1),
(464, 40, 'ios_ifa', '[ios_ifa]', NULL, NULL, 'iOS IDFA', 1),
(465, 40, 'google_aid', '[google_aid]', NULL, NULL, 'Google Advertising ID', 1),
(466, 40, 'zone', '[zone]', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(467, 40, 'clickid', '[clickid]', NULL, NULL, 'Click ID', 1),
(468, 40, 'country', '[country]', NULL, NULL, 'Country Code', 1),
(469, 41, 'tt_idfa', '{tt_idfa}', NULL, NULL, 'iOS IDFA (raw/ sha1/ md5)', 1),
(470, 41, 'tt_advertising_id', '{tt_advertising_id}', NULL, NULL, 'Google AID', 1),
(471, 41, 'aff_id', '{aff_id}', NULL, NULL, 'Sub publisher', 1),
(472, 41, 'tt_sub_aff', '{tt_sub_aff}', NULL, NULL, 'Publisher sub affiliate', 1),
(473, 41, 'tt_cid', '{tt_cid}', NULL, NULL, 'Taptica click ID', 1),
(474, 41, 'tt_adv_id', '{tt_adv_id}', NULL, NULL, 'Taptica advertiser ID', 1),
(475, 41, 'tt_country', '{tt_country}', NULL, NULL, 'Country Code', 1),
(476, 43, 'idfa', '%IDFA%', NULL, NULL, 'iOS IDFA', 1),
(477, 43, 'android_ad_id', '%ANDROID_AD_ID%', NULL, NULL, 'Google Advertising ID', 1),
(478, 43, 'campaign_id', '%CAMPAIGN_ID%', NULL, NULL, 'CrossInstall''s unique identifier for the campaign', 1),
(479, 43, 'country_code', '%COUNTRY_CODE%', NULL, NULL, 'Country Code', 1),
(480, 43, 'crossinstall_id', '%CROSSINSTALL_ID%', NULL, NULL, 'CrossInstall''s unique identifier for the click', 1),
(481, 43, 'device_type', '%DEVICE_TYPE%', NULL, NULL, 'The device type of the mobile device that clicked the campaign link. It will be either ''android'', ''iphone'', ''ipad'', or ''ipod'' (or it may be blank if the device type could not be properly identified)', 1),
(482, 43, 'ip', '%IP%', NULL, NULL, 'IP Address', 1),
(483, 43, 'publisher_id', '%PUBLISHER_ID%', NULL, NULL, 'A unique identifier for the publisher that sent in this click. May be used to track all of CrossInstall''s traffic sources for the clicks and conversions on your campaigns', 1),
(484, 45, 'advertising_id', '{advertising_id}', NULL, NULL, 'iOS IDFA/ Google Advertising ID', 1),
(485, 45, 'app_id', '{app_id}', NULL, NULL, 'Unique identifier for each campaign in Aarkis platform', 1),
(486, 45, 'click_id', '{click_id}', NULL, NULL, 'Unique identifier per click event', 1),
(487, 45, 'pub_id', '{pub_id}', NULL, NULL, 'Sub publisher', 1),
(488, 47, 'ios_ifa', '{ios_ifa}', NULL, NULL, 'iOS IDFA', 1),
(489, 47, 'google_aid', '{google_aid}', NULL, NULL, 'Google Advertising ID', 1),
(490, 47, 'affiliate_id', '{affiliate_id}', NULL, NULL, 'Sub publisher', 1),
(491, 47, 'ip', '{ip}', NULL, NULL, 'IP Address', 1),
(492, 47, 'country_code', '{country_code}', NULL, NULL, 'Country Code', 1),
(493, 47, 'transaction_id', '{transaction_id}', NULL, NULL, 'Click ID', 1),
(494, 49, 'xxxidfaxxx', 'xxxidfaxxx', NULL, NULL, 'iOS IDFA', 1),
(495, 49, 'xxxgoogleadidxxx', 'xxxgoogleadidxxx', NULL, NULL, 'Google Advertising ID', 1),
(496, 49, 'xxxtransidxxx', 'xxxtransidxxx', NULL, NULL, 'Transaction ID', 1),
(497, 49, 'xxxpubidxxx', 'xxxpubidxxx', NULL, NULL, 'Sub publisher', 1),
(498, 49, 'xxxsubidxxx', 'xxxsubidxxx', NULL, NULL, 'Creative', 1),
(499, 49, 'xxxipxxx', 'xxxipxxx', NULL, NULL, 'IP Address', 1),
(500, 5, 'ifa', '${ifa}', NULL, NULL, 'Identifier. iOS Identifier for Advertising (iOS 6+); Google Advertiser Identifier (GAID). String. Example: 67117c98-b534-4a4b-bc23-1418741984a5', 1),
(501, 5, 'odin', '${odin}', NULL, NULL, 'Identifier. Open Device Identifier Number (ODIN). String. Example: 82a53f1222f8781a5063a773231d4a7ee41bdd6f', 1),
(502, 5, 'mac', '${mac}', NULL, NULL, 'Identifier. The unique MAC address of the wifi hardware. String. Example: 56e5f5c0a08a', 1),
(503, 5, 'click_time', '${click_time}', NULL, NULL, 'Click time as recorded in unix time which is time in seconds. Integer. Example: 1372101648', 1),
(504, 5, 'game_id', '${game_id}', NULL, NULL, 'The PlayHaven specific game ID. Integer. Example: 1234', 1),
(505, 5, 'country', '${country}', NULL, NULL, 'Country is the 3 letter ISO. String. Example: USA', 1),
(506, 5, 'os', '${os}', NULL, NULL, 'OS is the raw OS string from the device. String. Example: iPhone+OS+6.0.2', 1),
(507, 5, 'language', '${language}', NULL, NULL, '2 character code that follows the ISO 639-1 standard. String. Example: en', 1),
(508, 5, 'hardware', '${hardware}', NULL, NULL, 'The raw hardware string associated with the device. String. Example: iPhone5,2 SGH-T999', 1),
(509, 5, 'campaign_id', '${campaign_id}', NULL, NULL, 'The specific campaign ID associated with this advertising campaign. Integer. Example: 1234', 1),
(510, 5, 'creative_id', '${creative_id}', NULL, NULL, 'The creative ID is the Playhaven specific ID associated with the creative displayed to the user that was clicked on. Integer. Example: 1234', 1),
(511, 5, 'install_time', '${install_time}', NULL, NULL, 'For conversions: timestamp of first launch. For Click Tracking, it will be 0 (zero). Integer. Example: 1372101648', 1),
(512, 51, 'idfa', '{idfa}', NULL, NULL, 'iOS IDFA', 1),
(513, 51, 'ip', '{ip}', NULL, NULL, 'IP Address', 1),
(514, 51, 'country_code', '{country_code}', NULL, NULL, 'Country Code (for instance, 86 for China)', 1),
(515, 51, 'sub_publisher', '{sub_publisher}', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(516, 53, 'ios_ifa', '${ios_ifa}', NULL, NULL, 'iOS IDFA', 1),
(517, 53, 'adid', '${adid}', NULL, NULL, 'Google Advertising ID', 1),
(518, 53, 'adkey', '${adkey}', NULL, NULL, 'Click ID', 1),
(519, 53, 'ipaddr', '${ipaddr}', NULL, NULL, 'IP Address', 1),
(520, 55, 'idfa', '{idfa}', NULL, NULL, 'iOS IDFA/ Google Advertising ID (md5 hashed)', 1),
(521, 55, '_site', '{_site}', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(522, 55, 'xuid', '{xuid}_advertiser ID', NULL, NULL, 'Session ID', 1),
(523, 57, 'ios_ifa', '{ios_ifa}', NULL, NULL, 'iOS IDFA', 1),
(524, 57, 'android_id', '{android_id}', NULL, NULL, 'Google Advertising ID', 1),
(525, 57, 'affiliate_id', '{affiliate_id}', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(526, 57, 'transaction_id', '{transaction_id}', NULL, NULL, 'Click ID', 1),
(527, 57, 'country_code', '{country_code}', NULL, NULL, 'Country Code', 1),
(528, 59, 'idfa', '%idfa%', NULL, NULL, 'iOS IDFA', 1),
(529, 59, 'adv_id', '%adv_id%', NULL, NULL, 'Google Advertising ID', 1),
(530, 59, 'guid', '%guid%', NULL, NULL, 'Click ID', 1),
(531, 59, 'carrier', '%carrier%', NULL, NULL, 'Carrier name', 1),
(532, 59, 'device', '%device%', NULL, NULL, 'Phone model', 1),
(533, 59, 'manufacturer', '%manufacturer%', NULL, NULL, 'Device manufacturer name', 1),
(534, 59, 'campaignid', '%campaignid%', NULL, NULL, 'Campaign ID', 1),
(535, 59, 'creativeid', '%creativeid%', NULL, NULL, 'Creative ID', 1),
(536, 59, 'ip', '%ip%', NULL, NULL, 'IP Address', 1),
(537, 59, 'country', '%country%', NULL, NULL, 'Country Code', 1),
(538, 59, 'dapp', '%dapp%', NULL, NULL, 'App ID', 1),
(539, 59, 'framework', '%framework%', NULL, NULL, 'Device OS Version', 1),
(540, 59, 'pubid', '%pubid%', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(541, 61, 'google_aid', '{google_aid}', NULL, NULL, 'Google Advertising ID', 1),
(542, 61, 'aff_sub5', '{aff_sub5}', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(543, 61, 'transaction_id', '{transaction_id}', NULL, NULL, 'Pinsight ID', 1),
(544, 63, 'idfa', '{{IDFA}}', NULL, NULL, 'iOS IDFA (md5 hashed)', 1),
(545, 63, 'gaidmd5', '{{GAIDMD5}}', NULL, NULL, 'Google Advertising ID (md5 hashed)', 1),
(546, 63, 'nendid', '{{NENDID}}', NULL, NULL, 'Nend click ID', 1),
(547, 63, 'spotid', '{{SPOTID}}', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(548, 65, 'idfa', 'idfa', NULL, NULL, 'RAW or SHA or MD5 iOS IDFA', 1),
(549, 65, 'gaid', 'gaid', NULL, NULL, 'RAW or SHA or MD5 Google Advertising ID', 1),
(550, 65, 'sub_publisher', 'sub_publisher', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(551, 65, 'rid', 'rid', NULL, NULL, 'Mobilemail click ID', 1),
(552, 65, 'sid', 'sid', NULL, NULL, 'Mobilemail Site ID (a campaign code on the advertiser''s dashboard)', 1),
(553, 67, 'idfa', '{idfa}', NULL, NULL, 'iOS IDFA/ Google Advertising ID', 1),
(554, 67, 'hashed_pid', '{hashed_pid}', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(555, 67, 'clickid', '{clickid}', NULL, NULL, 'Click ID', 1),
(556, 67, 'user', '{user agent}', NULL, NULL, 'URL encoded version of the HTTP user agent of the click', 1),
(557, 67, 'appid', '{appid}', NULL, NULL, 'Appsfire internal app ID', 1),
(558, 67, 'ip', '{ip}', NULL, NULL, 'IP Address', 1),
(559, 67, 'ccode', '{ccode}', NULL, NULL, 'Country Code', 1),
(560, 68, 'idfa', '${idfa}', NULL, NULL, 'iOS IDFA', 1),
(561, 68, 'adid', '${adid}', NULL, NULL, 'Google Advertising ID', 1),
(562, 68, 'ad_code', '${ad_code}', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(563, 68, 'country', '${country}', NULL, NULL, 'Country Code', 1),
(564, 7, 'idfa', '[IDFA]', NULL, NULL, 'iOS Identifier for Advertising (iOS 6+)', 1),
(565, 7, 'google_ad_id', '[GOOGLE_AD_ID]', NULL, NULL, 'Google AID', 1),
(566, 7, 'country_code', '[COUNTRY_CODE]', NULL, NULL, 'Country ISO code', 1),
(567, 7, 'ip_address', '[IP_ADDRESS]', NULL, NULL, 'IP Address', 1),
(568, 7, 'app_id', '[APP_ID]', NULL, NULL, 'The ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(569, 7, 'raw_ad_creative_id', '[RAW_AD_CREATIVE_ID]', NULL, NULL, 'Creative ID', 1),
(570, 7, 'ad_creative_name', '[AD_CREATIVE_NAME]', NULL, NULL, 'Creative name', 1),
(571, 70, 'ifa', 'ifa', NULL, NULL, 'iOS IDFA', 1),
(572, 70, 'gaid', 'gaid', NULL, NULL, 'Google Ad ID', 1),
(573, 70, 'uuid', 'uuid', NULL, NULL, 'Android ID (Amazon only)', 1),
(574, 70, 'country', 'country', NULL, NULL, 'Country Code', 1),
(575, 70, 'sup_pub', 'sup_pub', NULL, NULL, 'The ID of the app/ source where the ad is served', 1),
(576, 70, 'pub_app', 'pub_app', NULL, NULL, 'The name of the app/ source where the ad is served', 1),
(577, 70, 'sub_campaign', 'sub_campaign', NULL, NULL, 'The name of the campaign', 1),
(578, 70, 'creative_id', 'creative_id', NULL, NULL, 'Creative ID', 1),
(579, 70, 'creative_name', 'creative_name', NULL, NULL, 'Creative name', 1),
(580, 72, 'aff_sub', '{aff_sub}', NULL, NULL, 'iOS IDFA/ Google Advertising ID/ Android ID', 1),
(581, 72, 'mi_cid', '{mi_cid}', NULL, NULL, 'Massive Impact click identifier', 1),
(582, 74, 'idfa', '%idfa%', NULL, NULL, 'iOS IDFA', 1),
(583, 74, 'adv_id', '%adv_id%', NULL, NULL, 'Google Advertising ID', 1),
(584, 74, 'guid', '%guid%', NULL, NULL, 'Click ID', 1);
INSERT INTO `advertiser_macros` (`id`, `advertiser_id`, `name`, `macro`, `event`, `build`, `description`, `status_id`) VALUES
(585, 74, 'carrier', '%carrier%', NULL, NULL, 'Carrier name', 1),
(586, 74, 'device', '%device%', NULL, NULL, 'Phone model', 1),
(587, 74, 'manufacturer', '%manufacturer%', NULL, NULL, 'Device manufacturer name', 1),
(588, 74, 'campaignid', '%campaignid%', NULL, NULL, 'Campaign ID', 1),
(589, 74, 'creativeid', '%creativeid%', NULL, NULL, 'Creative ID', 1),
(590, 74, 'ip', '%ip%', NULL, NULL, 'IP Address', 1),
(591, 74, 'country', '%country%', NULL, NULL, 'Country Code', 1),
(592, 74, 'dapp', '%dapp%', NULL, NULL, 'App ID', 1),
(593, 74, 'framework', '%framework%', NULL, NULL, 'Device OS Version', 1),
(594, 74, 'pubid', '%pubid%', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(595, 76, 'aaid', '[AAID]', NULL, NULL, 'Google Advertising ID', 1),
(596, 76, 'clickid', '[ClickID]', NULL, NULL, 'Click ID', 1),
(597, 76, 'countrycode', '[countryCode]', NULL, NULL, 'Country Code', 1),
(598, 76, 'idfa', '[IDFA]', NULL, NULL, 'iOS IDFA', 1),
(599, 76, 'site_id', '[SITE_ID]', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(600, 78, 'idfa', '{idfa}', NULL, NULL, 'iOS IDFA', 1),
(601, 78, 'sub_publisher', '{sub_publisher}', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(602, 78, 'ip', '{ip}', NULL, NULL, 'IP Address', 1),
(603, 78, 'country_code', '{country_code}', NULL, NULL, 'Country Code (for instance, 86 for China)', 1),
(604, 79, 'ifa', '$!{IFA}', NULL, NULL, 'Google Advertising ID / iOS IDFA', 1),
(605, 79, 'app_id', '$!{APP_ID}', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(606, 79, 'turn_uuid', '$!{TURN_UUID}', NULL, NULL, 'Turn internal click ID', 1),
(607, 79, 'device_sha1', '$!{DEVICE_SHA1}', NULL, NULL, 'Device', 1),
(608, 79, 'platform_sha1', '$!{PLATFORM_SHA1}', NULL, NULL, 'Platform', 1),
(609, 79, 'mac_sha1', '$!{MAC_SHA1}', NULL, NULL, 'MAC address', 1),
(610, 83, 'advertising_id', '{advertising_id}', NULL, NULL, 'Google Advertising ID', 1),
(611, 83, 'transaction_id', '{transaction_id}', NULL, NULL, 'Click ID', 1),
(612, 85, 'idfa', '|idfa|', NULL, NULL, 'iOS IDFA', 1),
(613, 85, 'gaid', '|gaid|', NULL, NULL, 'Google Advertising ID', 1),
(614, 85, 'zoneid', '|zoneid|', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(615, 85, 'idc', '|idc|', NULL, NULL, 'Click ID', 1),
(616, 87, 'idfa', '{idfa}', NULL, NULL, 'iOS IDFA', 1),
(617, 87, 'sub_publisher', '{sub_publisher}', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(618, 87, 'ip', '{ip}', NULL, NULL, 'IP Address', 1),
(619, 87, 'country_code', '{country_code}', NULL, NULL, 'Country Code (for instance, 86 for China)', 1),
(620, 89, 'android_id', '$ANDROID_ID$', NULL, NULL, 'Google Advertising ID / iOS IDFA', 1),
(621, 89, 'subsubid', '$SUBSUBID$', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(622, 89, 'adid', '$ADID$', NULL, NULL, 'Click ID', 1),
(623, 89, 'subid', '$SUBID$', NULL, NULL, 'traffic segment ID', 1),
(624, 89, 'action', '$ACTION$', NULL, NULL, 'Action (for instance, I stands for Install)', 1),
(625, 89, 'cpi', '$CPI$', NULL, NULL, 'CPI', 1),
(626, 9, 'acquisition_identifier', '{acquisition_identifier}', NULL, NULL, 'Acquisition ID - mNectar''s identifier for the ad being installed', 1),
(627, 9, 'ios_ifa', '{ios_ifa}', NULL, NULL, 'iOS Identifier for Advertisers aka ''iOS IDFA''', 1),
(628, 9, 'android_ifa', '{android_ifa}', NULL, NULL, 'Android Advertising Identifier - Google''s Play Store ID for Advertisers', 1),
(629, 9, 'android_id_sha1', '{android_id_sha1}', NULL, NULL, 'Android ID - SHA1 of Android ID', 1),
(630, 9, 'remote_ip_address', '{remote_ip_address}', NULL, NULL, 'Remote IP Address', 1),
(631, 9, 'conversion_timestamp', '{conversion_timestamp}', NULL, NULL, 'Conversion timestamp', 1),
(632, 9, 'click_id', '{click_id}', NULL, NULL, 'mNectar''s unique click identifier', 1),
(633, 9, 'ad_id', '{ad_id}', NULL, NULL, 'Unique id for each creative line item in mNectar''s system', 1),
(634, 9, 'ad_unit_id', '{ad_unit_id}', NULL, NULL, 'mNectar''s anonymous content id', 1),
(635, 9, 'publisher_id', '{publisher_id}', NULL, NULL, 'mNectar''s anonymous publisher id', 1),
(636, 91, 'identifier', '{identifier}', NULL, NULL, 'Click ID', 1),
(637, 91, 'sub_publisher', '{sub_publisher}', NULL, NULL, 'the ID of the publisher where the ad served, if the advertiser wants to do quality adjustments by publisher', 1),
(638, 93, 'sessionid', '[SESSIONID]', NULL, NULL, 'Click ID', 1),
(639, 93, 'campaignid', '[campaignid]', NULL, NULL, 'Smart-C campaign ID', 1),
(640, 93, 'asid', '[ASID]', NULL, NULL, 'Media ID', 1),
(641, 95, 'identifier', '{identifier}', NULL, NULL, 'A URL-encoded string which identifies an advertisement click on a unique device', 1),
(642, 95, 'google_aid', '{google_aid}', NULL, NULL, 'Device Google Advertising Id', 1),
(643, 95, 'google_ad_tracking', '{google_ad_tracking}', NULL, NULL, 'Google Advertising ID', 1),
(644, 95, 'said', '{said}', NULL, NULL, 'A unique identifier of the app in which the advertisement appeared.', 1),
(645, 95, 'package_name', '{package_name}', NULL, NULL, 'Android package name for the advertised app.', 1),
(646, 95, 'timestamp', '{timestamp}', NULL, NULL, 'Date and time of the click in ISO8601 datetime format. Example: 2013-02-22T16:01:23Z.', 1),
(647, 97, 'ex_token', '{ex_token}', NULL, NULL, 'A URL-encoded string which identifies an advertisement click on a unique device', 1),
(648, 97, 'google_aid', '{google_aid}', NULL, NULL, 'Device Google Advertising Id', 1),
(649, 97, 'google_ad_tracking', '{google_ad_tracking}', NULL, NULL, 'Google Advertising ID', 1),
(650, 97, 'media_id', '{media_id}', NULL, NULL, 'The Publisher Id of the source media', 1),
(651, 99, 'android_advertiser_id', '{ANDROID_ADVERTISER_ID}', NULL, NULL, 'Android Advertiser ID', 1),
(652, 99, 'idfa', '{IDFA}', NULL, NULL, 'iOS Advertiser ID', 1),
(653, 99, 'publisher_id', '{PUBLISHER_ID}', NULL, NULL, 'Publisher ID', 1),
(654, 99, 'impression_id', '{IMPRESSION_ID}', NULL, NULL, 'Click (to pass @ post back)', 1);